# Nutzt Windows als Build-Umgebung
image: Visual Studio 2022

# Node.js Version festlegen
environment:
  nodejs_version: "18"

# Vor dem Build ausführen:
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install -g electron-builder

# Der eigentliche Build-Prozess
build_script:
  - npm run build
  - electron-builder --win

# Artefakte speichern (die fertige EXE-Datei)
artifacts:
  - path: dist/*.exe
    name: ElectronApp
